Added a check when performing a post.
sampsyo/wideq pull request #102
Opened 2020-05-30 08:43 UTC by beele

If a device control was performed, release the control back. Also refactored the logic a bit so the both the api_root and path are passed to the post method

2020-05-30 08:48 UTC, ncovercash approved these changes

2020-05-30 08:50 UTC, beele commented
80 chars FFS

2020-05-30 08:53 UTC, ncovercash commented
Missed a line! 🙃

For real though, 100 or 120 if any at all is much saner these days

2020-05-30 12:18 UTC, sampsyo requested changes
Thanks for getting this started! I have a couple of comments within, and I would love to _not_ add the extra parameter to `lgedm_post` for now. Instead, let's just send a second `lgedm_post` from the locations that need it.

One other thing I'm worried about is that this will be wasteful for some situations… that is, every request will now turn into two requests. For some situations where you want to make multiple requests, it seems bad that we'll now be doing 2n service requests instead of n+1 (the original n requests, plus just one `delControlPermission` at the very end). Probably not a big deal, but maybe worth worrying about… we could also require clients to explicitly relinquish control, which would avoid the problem.

2020-05-30 12:18 UTC, sampsyo commented on wideq/core.py
> +GATEWAY_URL = 'https://kic.lgthinq.com:46030'
Let's leave this change where we split up the base URL and path out for now—it looks interesting, but I would love to review it carefully in a separate PR.

2020-05-30 12:18 UTC, sampsyo commented on wideq/core.py
> +        if "rtiControl" in path:
Let's move this from `lgedm_post`, which is a low-level communication primitive, to the places that actually use `rtiControl`. That way we won't have to check what kind of request we're doing; we'll do it in exactly the right place "by construction."

I think that might juts mean `set_device_controls`, or possibly that and `get_device_config`. Can we try it with just the former, and see if it works, and if not, do the latter?

2020-05-31 23:49 UTC, ncovercash commented
From my experience, a delControlPermission is needed for every control request sent, otherwise the oofficial mobile app locks out for a while

2020-06-01 00:37 UTC, sampsyo commented
Sure, makes sense—but let's put it where we initiate those `rtiControl` control calls to `lgedm_post` rather than inside the function based on an `if` to see what type of request it is.

2020-06-01 09:46 UTC, ncovercash commented
Understandable!

2025-08-25 06:24 UTC, closed without merging